field_focus_person:
  label: Department Head
  description: The head of the department
  entity_type: taxonomy_term
  
field_focus_people:
  label: "Department Faculty & Staff"
  entity_type: taxonomy_term

field_focus_location:
  label: Department Location
  description: Where this department is located
  entity_type: taxonomy_term
