<?php
/**
 * Implements hook_focus_node_type()
 */
function focus_sponsor_focus_node_type() {
    return array('focus_sponsor');
}

/**
 * Implements hook_focus_field_group()
 */
function focus_sponsor_focus_field_group() {
    return array('focus_sponsor');
}

/**
 * Implements hook_form()
 * 
 * This function must exist in order for this content type to appear at admin/stucture/types
 */
function focus_sponsor_form($node, &$form_state) {
    return array();
}
