global:
  admin_menu_components:
    admin_menu.icon: 1
    admin_menu.menu: 1
    admin_menu.account: 1
    admin_menu.search:
    admin_menu.users:
  date_format_long: l, F j, Y - g:ia
  date_format_medium: F j, Y - g:ia
  date_format_short: M j Y - g:ia
  date_format_tiny: n/j/y
  date_format_year: "Y"
  date_format_time: g:ia
  file_default_scheme: public
  file_private_path: sites/default/files/private
  file_public_path: sites/default/files
  imageapi_optimize_service: smushit
  imageapi_optimize_toolkit: gd
  image_jpeg_quality: 80
  image_toolkit: imageapi_optimize
  jira_issue_collector_pages: media/browser
  jira_issue_collector_visibility: 0
  jquery_update_compression_type: min
  jquery_update_jquery_cdn: google
  jquery_update_jquery_version: 1.8
  media__wysiwyg_browser_plugins: 
    upload
    media_default--media_browser_1
    media_default--media_browser_my_files
  media__wysiwyg_upload_directory: media
  menu_expanded:
    main-menu
  menu_main_links_source: main-menu
  menu_secondary_links_source: user-menu
  node_admin_theme: 1
  views_ui_show_advanced_help_warning: ~

webform:
  ant_pattern_webform:
  ant_php_webform: 0
  ant_webform: 0
  menu_options_webform:
    main-menu
  menu_parent_webform: "main-menu:0"
  node_options_webform:
    status
  node_preview_webform: 1
  node_submitted_webform: 0
  structural_childview_webform: 0
  structural_enabled_webform: 1 # FOCUS_STRUCTURE_OPTIONAL_NO
  structural_children_webform: []