body:
  label: Event Description

field_focus_primary_image:
  label: Event Image
  description: Image associated with this event
  
field_focus_gallery_image:
  label: Gallery Images
  description: Gallery of images associated with this event
  
field_focus_location:
  label: Event Location
  description: Where this event takes place
  
field_focus_calendar_date:
  label: Event Date
  description: Start / End date for this event
  
field_focus_download:
  label: Downloads
  description: Files associated with this event
  
field_focus_media:
  label: Media
  description: Media associated with this event
  
field_focus_sidebar:
  label: Event Sidebar
  description: Sidebar associated with this event
