# @see https://gist.github.com/dvessel/1610551

source "http://rubygems.org"

group :development do
  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', :require => false # Linux
  gem 'rb-fsevent', :require => false # Mac OSX
  gem 'rb-fchange', :require => false # Windows
  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass'                 # Framework built on Sass.
  gem 'guard'                   # Guard event handler.
  gem 'guard-compass'           # Compile on sass/scss change.
  gem 'guard-shell'             # Run shell commands.
  gem 'guard-livereload'        # Browser reload.
  gem 'yajl-ruby'               # Faster JSON with LiveReload in the browser.
  gem 'zen-grids'               # The Grid.
  gem 'dropcloth'               # A css neutralizer for Drupal.
end