field_focus_tags:
  label: Tags
  type: taxonomy_term_reference
  cardinality: -1 # FIELD_CARDINALITY_UNLIMITED
  widget:
    type: taxonomy_autocomplete
    settings:
      autocomplete_path: taxonomy/autocomplete
    module: taxonomy
  settings:
    allowed_values:
      0:
        vocabulary: focus_tag
        parent: 0