group_content:
  data:
    label: "Title & Content"
    children:
      title
      body

group_images:
  data:
    label: Images
    children:
      field_focus_thumbnail
      field_focus_primary_image
      field_focus_gallery_image
      
group_media:
  data:
    label: Associated Files
    children:
      field_focus_download
      field_focus_audio
      field_focus_video
      
group_meta:
  data:
    label: Meta Tags
    children:
      field_focus_tags
      