<?php
/**
 * @file
 * @todo
 */

/**
 * Implements hook_views_api().
 */
function focus_article_views_api() {
    return array(
        'api' => 3,
    );
}

/**
 * Implements hook_toolkit_api().
 */
function focus_article_toolkit_api() {
    return array(
        'api' => 1,
    );
}

/**
 * Implements hook_form().
 * 
 * This function must exist in order for this content type to appear at admin/stucture/types
 */
function focus_article_form($node, &$form_state) {
    return array();
}
