field_focus_location:
  label: Location
  type: taxonomy_term_reference
  widget:
    type: taxonomy_autocomplete
    settings:
      autocomplete_path: taxonomy/autocomplete
    module: taxonomy
  settings:
    allowed_values:
      0:
        vocabulary: focus_location
        parent: 0