global:
  description: This context will be active throughout your site
  tag: Global
  conditions:
    sitewide:
      values:
        1: 1
  reactions:
    debug:
      debug: 1
  condition_mode: 0
  
home:
  description: This context will be active on the <front> page only
  tag: Home
  conditions:
    path:
      values:
        <front>
  reactions:
    debug:
      debug: 1
  condition_mode: 1
  
inner:
  description: This context is used for all pages, except the home page
  tag: Inner Pages
  conditions:
    path:
      values:
        ~<front>: '~<front>'
        ~*/edit: '~*/edit'
        ~media/browser: '~media/browser'
  reactions:
    debug:
      debug: 1
  condition_mode: 1
  
search:
  description: This context is used for all search pages
  tag: Inner Pages
  conditions:
    path:
      values:
        search/*: 'search/*'
  reactions:
    debug:
      debug: 1
  condition_mode: 1                         
  
content_default:
  description: This context is used for the majority of standard content types
  tag: Inner Pages
  conditions:
    node:
      values: !php:_webtree_contexts_get
      options:
        node_form: 0
    path:
      values:
        ~<front>: '~<front>'
        ~*/edit: '~*/edit'
        ~media/browser: '~media/browser'
  reactions:
    debug:
      debug: 1
    delta:
      delta_template: page_default
    block:
      blocks:
        views-in_this_section-its:
          module: views
          delta: in_this_section-its
          region: sidebar_first
          weight: -10
        views-downloads-downloads:
          module: views
          delta: downloads-downloads
          region: sidebar_first
          weight: -9
        views-gallery-gallery:
          module: views
          delta: gallery-gallery
          region: sidebar_first
          weight: -8
        views-sidebars-sidebars:
          module: views
          delta: sidebars-sidebars
          region: sidebar_first
          weight: -7
  condition_mode: 1
  
section_default:
  description: This context is used for the majority of section pages
  tag: Sections
  conditions:
    node:
      values: !php:_webtree_contexts_get
      options:
        node_form: 0
  reactions:
    debug:
      debug: 1
    delta:
      delta_template: section_default
    block:
      blocks:
        views-in_this_section-its:
          module: views
          delta: in_this_section-its
          region: sidebar_first
          weight: -10
  condition_mode: 0