<?php
/**
 * @file
 * @todo
 */

/**
 * Implements hook_views_api().
 */
function focus_sidebar_views_api() {
    return array(
        'api' => 3,
    );
}

/**
 * Implements hook_focus_content_type()
 */
function focus_sidebar_focus_content_type() {
    return array('focus_sidebar');
}

/**
 * Implements hook_focus_field_group()
 */
function focus_sidebar_focus_field_group() {
    return array('focus_sidebar');
}

/**
 * Implements hook_focus_fields().
 */
function focus_sidebar_focus_fields() {
    return array('focus_sidebar');
}

/**
 * Implements hook_form()
 * 
 * This function must exist in order for this content type to appear at admin/stucture/types
 */
function focus_sidebar_form($node, &$form_state) {
    return array();
}
