default: 1
user_choose: 0
show_toggle: 1
theme: advanced
language: en
access: 1
toolbar_loc: top
toolbar_align: left
path_loc: bottom
resizing: 1
verify_html: 1
preformatted: 0
convert_fonts_to_spans: 1
remove_linebreaks: 1
apply_source_formatting: 0
paste_auto_cleanup_on_paste: 0
css_setting: theme
css_path: 
css_classes: 
buttons: 
block_formats:
  p
  h2
  h3
  h4
  h5
  h6
  div
access_pages: 
  node/*
  user/* 
  comment/*