field_focus_region:
  label: Tags
  type: taxonomy_term_reference
  widget:
    type: taxonomy_autocomplete
    settings:
      autocomplete_path: taxonomy/autocomplete
    module: taxonomy
  settings:
    allowed_values:
      0:
        vocabulary: focus_region
        parent: 0