# set node type specific settings if different from Drupal default
#
# format as variable_name:value
ant_pattern:
ant_php: 0
ant: 0
menu_options: []
menu_parent: "main-menu:0"
node_options:
  status
  revision
node_preview: 1
node_submitted: 0
focus_structure_children_view: 0
focus_structure_enabled: 1 # FOCUS_STRUCTURE_OPTIONAL_NO
focus_structure_children: []
