focus_event:
  menu_options:
    events
  menu_parent:
    "events:0"
  structural_hidden: 0 # Display in Navigation? STRUCTURAL_NEVER
  structural_enabled: 2 # STRUCTURAL_OPTIONAL_YES

focus_section:
  menu_options:
    events
  structural_children:
    focus_event
  structural_extralinks: 1