body:
  label: Course Description

field_focus_download:
  label: Downloads
  description: Files associated with this course
  
field_focus_person:
  label: Instructor
  description: The course instructor
  
field_focus_courses:
  label: Prerequisites
  description: Courses required to take this course
  
field_focus_semester:
  label: Semester(s)
  description: Semesters this course is offered
  
field_focus_sidebar:
  label: Page Sidebar
  description: Sidebar associated with this course
  
field_focus_location:
  label: Location
  description: Where this course is offered
