field_focus_courses:
  label: Courses
  type: entityreference
  cardinality: -1 # FIELD_CARDINALITY_UNLIMITED
  widget:
    type: entityreference_autocomplete
  settings:
    target_type: node
    handler_settings:
      target_bundles:
        focus_course: focus_course