field_focus_news_tag:
  label: News Tag
  type: taxonomy_term_reference
  cardinality: -1 # FIELD_CARDINALITY_UNLIMITED
  widget:
    type: taxonomy_autocomplete
    settings:
      autocomplete_path: taxonomy/autocomplete
    module: taxonomy
  settings:
    allowed_values:
      0:
        vocabulary: focus_news_tag
        parent: 0
