<?php
/**
 * Implements hook_focus_content_type()
 */
function focus_person_focus_content_type() {
    return array('focus_person');
}

/**
 * Implements hook_focus_field_group()
 */
function focus_person_focus_field_group() {
    return array('focus_person');
}

/**
 * Implements hook_focus_fields().
 */
function focus_person_focus_fields() {
    return array('focus_person');
}

/**
 * Implements hook_form()
 * 
 * This function must exist in order for this content type to appear at admin/stucture/types
 */
function focus_person_form($node, &$form_state) {
    return array();
}
