<?php
/**
 * @file
 * @todo
 */
 
module_load_include('inc', 'focus_tools', 'includes/constants');
module_load_include('inc', 'focus_tools', 'includes/helpers');
module_load_include('inc', 'focus_tools', 'includes/api');

/**
 * Implements hook_menu().
 */
function focus_tools_menu() {
    
    $items['admin/focus/fields/rebuild'] = array(
        'title'            => 'Rebuild FOCUS Fields',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('focus_tools_fields_rebuild'),
        'access arguments' => array('rebuild focus fields'),
        'file'             => 'includes/config.inc',
        'type'             => MENU_NORMAL_ITEM,
        'weight'           => -998,
    );
    
    return $items;
    
}

/**
 * Implements hook_node_info().
 */
function focus_tools_node_info() {
    $types = array();
    
    foreach (module_implements('focus_content_type') as $module) {
        foreach (module_invoke($module, 'focus_content_type') as $type) {
            if ($settings = _focus_tools_bundle_get($module)) {
                $types[$type] = $settings;
            }
        }
    }
    
    return $types;
}

/**
 * Implements hook_focus_content_type().
 */
function focus_tools_focus_content_type() {
    return array('focus');
}

/**
 * Implements hook_permission().
 */
function focus_tools_permission() {
    $permissions['rebuild focus fields'] = array(
        'title' => t('Rebuild FOCUS Fields'),
        'description' => t('Allows users to rebuild FOCUS field structure from code.'),
        'restrict access' => TRUE,
    );
    
    return $permissions;
}

/**
 * Implements hook_ctools_plugin_api()
 */
function focus_tools_ctools_plugin_api($module, $api) {
    if ($module == 'field_group' && $api == 'field_group') {
        return array('version' => 1);
    }
}

/**
 * Implements hook_field_group_info()
 */
function focus_tools_field_group_info() {
    $field_groups = array();
    
    $types = module_invoke_all('focus_field_group');
    
    foreach ($types as $type) {
        if ($field_group = _focus_tools_field_group_get($type)) {
            $field_groups += $field_group;
        }
    }
    
    return $field_groups;
}
