<?php
/**
 * @file
 * @todo
 */

/**
 * Implements hook_views_default_views()
 */
// function focus_secondary_sidebar_views_default_views() {
    // $view = new View;
    // $view->name = 'sidebars';
    // $view->description = '';
    // $view->tag = 'default';
    // $view->base_table = 'node';
    // $view->human_name = 'Sidebars';
    // $view->core = 7;
    // $view->api_version = '3.0';
    // $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
//     
    // /* Display: Master */
    // $handler = $view->new_display('default', 'Master', 'default');
    // $handler->display->display_options['use_more_always'] = FALSE;
    // $handler->display->display_options['access']['type'] = 'perm';
    // $handler->display->display_options['cache']['type'] = 'none';
    // $handler->display->display_options['query']['type'] = 'views_query';
    // $handler->display->display_options['exposed_form']['type'] = 'basic';
    // $handler->display->display_options['pager']['type'] = 'some';
    // $handler->display->display_options['pager']['options']['items_per_page'] = '5';
    // $handler->display->display_options['style_plugin'] = 'default';
    // $handler->display->display_options['row_plugin'] = 'fields';
    // /* Relationship: Entity Reference: Referenced Entity */
    // $handler->display->display_options['relationships']['field_focus_sidebar_target_id']['id'] = 'field_focus_sidebar_target_id';
    // $handler->display->display_options['relationships']['field_focus_sidebar_target_id']['table'] = 'field_data_field_focus_sidebar';
    // $handler->display->display_options['relationships']['field_focus_sidebar_target_id']['field'] = 'field_focus_sidebar_target_id';
    // $handler->display->display_options['relationships']['field_focus_sidebar_target_id']['label'] = 'Sidebar';
    // $handler->display->display_options['relationships']['field_focus_sidebar_target_id']['required'] = TRUE;
    // /* Field: Content: Title */
    // $handler->display->display_options['fields']['title']['id'] = 'title';
    // $handler->display->display_options['fields']['title']['table'] = 'node';
    // $handler->display->display_options['fields']['title']['field'] = 'title';
    // $handler->display->display_options['fields']['title']['relationship'] = 'field_focus_sidebar_target_id';
    // $handler->display->display_options['fields']['title']['label'] = '';
    // $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    // $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    // $handler->display->display_options['fields']['title']['element_type'] = 'h6';
    // $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
    // $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
    // /* Field: Content: Body */
    // $handler->display->display_options['fields']['body']['id'] = 'body';
    // $handler->display->display_options['fields']['body']['table'] = 'field_data_body';
    // $handler->display->display_options['fields']['body']['field'] = 'body';
    // $handler->display->display_options['fields']['body']['relationship'] = 'field_focus_sidebar_target_id';
    // $handler->display->display_options['fields']['body']['label'] = '';
    // $handler->display->display_options['fields']['body']['element_label_colon'] = FALSE;
    // /* Sort criterion: Content: Sidebar (field_focus_sidebar:delta) */
    // $handler->display->display_options['sorts']['delta']['id'] = 'delta';
    // $handler->display->display_options['sorts']['delta']['table'] = 'field_data_field_focus_sidebar';
    // $handler->display->display_options['sorts']['delta']['field'] = 'delta';
    // $handler->display->display_options['sorts']['delta']['relationship'] = 'field_focus_sidebar_target_id';
    // /* Contextual filter: Content: Nid */
    // $handler->display->display_options['arguments']['nid']['id'] = 'nid';
    // $handler->display->display_options['arguments']['nid']['table'] = 'node';
    // $handler->display->display_options['arguments']['nid']['field'] = 'nid';
    // $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
    // $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
    // $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
    // $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
    // $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
    // /* Filter criterion: Content: Published */
    // $handler->display->display_options['filters']['status']['id'] = 'status';
    // $handler->display->display_options['filters']['status']['table'] = 'node';
    // $handler->display->display_options['filters']['status']['field'] = 'status';
    // $handler->display->display_options['filters']['status']['value'] = 1;
    // $handler->display->display_options['filters']['status']['group'] = 1;
    // $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
//     
    // /* Display: Block */
    // $handler = $view->new_display('block', 'Block', 'sidebars');
    // $handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
    // $handler->display->display_options['block_description'] = 'Sidebars';
//     
    // // Add sidebar view
    // $views[$view->name] = $view;
//     
    // return $views;
// }
