ant: 1 # enable auto nodetitle
ant_php: 0 # don't use php for auto nodetitle
ant_pattern: "[node:field-focus-name:field_focus_first_name] [node:field-focus-name:field_focus_last_name]"
focus_contexts: 
  page_default
